### ISSUE TITLE
Upgrade to Node v18.16.1

### ISSUE THREAD

**Issue by forrestwilkins** [forrestwilkins/praxis#123]
Node 18 comes with a wide variety of improvements and will be supported until 2025.

https://nodesource.com/blog/11-features-nodeJS-18-to-try

**Comment by tjdavenport** [comment]
Hey! I'm down to help with this. Could you accept my invitation on LinkedIn? :)

**Comment by forrestwilkins** [comment]
Hey @tjdavenport, sounds good! I'll take a look on LinkedIn

**Comment by tjdavenport** [comment]
@forrestwilkins can you also check your LinkedIn messages :p
